spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/minidropbox
    username: postgres
    password: 9936287082
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: my-super-secret-key-for-jwt-must-be-at-least-32-bytes-long
  expiration: 86400000 # 1 day
